config/routes.rb
Rails.application.routes.draw do
  get 'stores/index'
  get 'stores/new'
  get 'stores/show'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  get 'principal/', to: "stores#index"

  # Defines the root path route ("/")
  root "stores#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/vehicle.rb
class Vehicle < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/stores_controller.rb
class StoresController < ApplicationController
  def index
  end

  def new
  end

  def show
    @todos = Vehicle.all
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/stores_helper.rb
module StoresHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Automotora</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "miestilo", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-9ndCyUaIbzAi2FUVXJi0CjmCapSmO7SnpJef0486qhLnuZ2cdeRhO02iuK6FUUVM" crossorigin="anonymous">
  </head>

  <body>

    <nav class="navbar navbar-expand-lg bg-body-tertiary">
      <div class="container">
        <a class="navbar-brand" href="#">Navbar</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav me-auto mb-2 mb-lg-0">
            <li class="nav-item">
              <%= link_to "Home", "/", class: "nav-link active" %>
            </li>
            <li class="nav-item">
              <%= link_to "Show", stores_show_path, class: "nav-link active" %>
            </li>
          </ul>
        </div>
      </div>
    </nav>

    <div class="container mt-5">
      <%= yield %>
    </div>

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-geWF76RCwLtnZ8qwWowPQNguL3RmwHVBC9FhGdlKrxdiJJigb/j/68SIy3Te4Bkz" crossorigin="anonymous"></script>
  </body>
</html>

app/views/layouts/layout2.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Automotora</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "miestilo2", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>

  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/stores/index.html.erb
<h1>Stores#index</h1>
<p>Find me in app/views/stores/index.html.erb</p>
<img src="<%= asset_path 'auto.jpg' %>" class="miimagenlinda">
<br>
<%= image_tag 'auto.jpg', class: "miimagenlinda" %>

app/views/stores/new.html.erb
<h1>Stores#new</h1>
<p>Find me in app/views/stores/new.html.erb</p>

app/views/stores/show.html.erb
<h1>Stores#show</h1>
<p>Find me in app/views/stores/show.html.erb</p>

<% @todos.each do |v| %>
    <p><%= v.brand %></p>
<% end %>